# Generated by Django 3.1.7 on 2021-04-03 17:12

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210402_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_photo',
            field=models.ImageField(default='default.png', upload_to=users.utils.upload_image_path, verbose_name='Display Photo'),
        ),
    ]
