# Generated by Django 3.1.7 on 2021-04-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210403_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Phone Number'),
        ),
    ]
