# Generated by Django 3.1.7 on 2021-05-25 17:41

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210525_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='blood_group',
            field=models.CharField(choices=[('AP', 'A+'), ('AN', 'A-'), ('BP', 'B+'), ('BN', 'B-'), ('ABP', 'AB+'), ('ABN', 'AB+'), ('OP', 'O+'), ('ON', 'O-')], max_length=4),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='display_photo',
            field=models.ImageField(default='default.png', upload_to=users.utils.user_profile_image_file, verbose_name='Display Photo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, verbose_name='Gender'),
        ),
    ]
