# Generated by Django 3.1.7 on 2021-05-27 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210526_1655'),
        ('users', '0007_auto_20210525_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='blood_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.blood'),
        ),
    ]
