# Generated by Django 3.1.7 on 2021-06-02 20:43

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210527_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_photo',
            field=models.ImageField(upload_to=users.utils.user_profile_image_file, verbose_name='Display Photo'),
        ),
    ]
