# Generated by Django 3.1.7 on 2021-06-11 15:39

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210603_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_photo',
            field=models.ImageField(blank=True, upload_to=users.utils.user_profile_image_file, verbose_name='Display Photo'),
        ),
    ]
