# Generated by Django 3.1.7 on 2021-04-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('completed', 'Completed')], default='a', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='blood_group',
            field=models.CharField(choices=[('A_P', 'A+'), ('A_N', 'A-'), ('B_P', 'B+'), ('B_N', 'B-'), ('AB_P', 'AB+'), ('AB_N', 'AB+'), ('O_P', 'O+'), ('O_N', 'O-')], max_length=4),
        ),
    ]
