# Generated by Django 3.1.7 on 2021-05-26 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210526_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='locallevel',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='blood_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.blood'),
        ),
    ]
