# Generated by Django 3.1.7 on 2021-05-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210526_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='LocalLevel',
        ),
    ]
