# Generated by Django 3.1.7 on 2021-06-27 13:32

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210603_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='image',
            field=models.ImageField(blank=True, upload_to=users.utils.request_blood_image_file),
        ),
    ]
