# Generated by Django 3.1.7 on 2021-07-15 17:11

from django.db import migrations


def populate_blood_type(apps, schema_editor):
    blood_dict = {
        'A+': 'a',
        'A-': 'a-',
        'B+': 'b',
        'B-': 'b-',
        'AB+': 'ab',
        'AB-': 'ab-',
        'O+': 'o',
        'O-': 'o-',
    }
    BloodType = apps.get_model('core', 'Blood')
    for blood_type, value in blood_dict.items():
        BloodType.objects.create(group=blood_type, slug=value)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_request_image'),
    ]

    operations = [
         migrations.RunPython(populate_blood_type)
    ]
